### ISSUE TITLE
Severity: Error Log Message: Unable to update subscriptions for banned member

### ISSUE THREAD

**Issue by pvledoux** [monooso/mailchimp_subscribe.ee_addon#4]
Hi Stephen,

I have a little issue here when a new member is subscribing. I received (thanks to Omnilog) the following error:

```
OmniLog was instructed to notify the site administrator of the following log entry. Add-on Name: MailChimp Subscribe Log Entry     Date: Wed, 23 May 2012 18:00:07 +0100 Severity: Error Log Message: Unable to update subscriptions for banned member     Blablablalb (1234) (error code: 0 Log Extended Data: Control Panel URL:  --- END OF MESSAGE --- 
```

I found the line throwing that error: 1213, but I'm not sure how I can resolved the issue. In the conditional line 1211, should  we test if we are not updating?

```
// Is the member banned?
if (in_array($member['group_id'], array('2', '4')) && $update === TRUE)
{
  throw new MCS_Data_exception('Unable to update subscriptions for banned
    member ' .$member['screen_name'] .' (' .$member_id .')');
}
```

It's not blocking, but I would prefer to stop being bugged by that error ;)

Cheers!

Pv

**Comment by manifestuk** [comment]
Hi Pv,

The existing conditional should only catch Pending and Banned Members:

```
// 2 = Pending; 4 = Banned
if (in_array($member['group_id'], array('2', '4')))
```

Unless new Members are being automatically added to the Banned Member Group, I'm a bit confused as to why you're running into this problem. Am I missing something obvious (perfectly possible, as it's been a while since I've really looked at this add-on)?

Cheers,
Stephen

**Comment by pvledoux** [comment]
Hi,

well I'm a bit confused too, I'm going to var_dump a bit, I didn't had 
time last days as I spent lot of time drinking beers in Leiden during my 
free time...

Pv

**Comment by manifestuk** [comment]
Wait, you're in Leiden? Grab me and say hello!

**Comment by pvledoux** [comment]
Arf sorry we had to hurry to catch the train to Brussels and I did not had
the occasion to talk to you (and lot of others...frustrating)

We will definitely have a beer next year ;)

I will make some test for that issue tomorrow and let you know.

Cheers!

Pv
Le 31 mai 2012 14:01, "Stephen Lewis" <
reply@reply.github.com>
a écrit :
