### ISSUE TITLE
Not saving settings in extension

### ISSUE THREAD

**Issue by jeramiah** [monooso/mailchimp_subscribe.ee_addon#5]
I tried to email you but it bounced back to me.  It looks like the extension is not saving any settings.  I can say it's successfully importing the lists from mailchimp using the API KEY but it's not saving any of my settings.  I have this included on my registration form with the corresponding member fields created and trigger fields... yet nothing gets added to my mailchimp list.  Any ideas -- anyone else experiencing this?
![settings](https://f.cloud.github.com/assets/3238304/58021/a460436c-5b61-11e2-888c-4b9519aef8c9.png)

**Comment by jeramiah** [comment]
Well, I realized that I had to select the checkboxes, and then it was able to save my settings.  The only problem is, when a member registers it's still not updating mailchimp with that email address.  Any ideas?  Am I missing a step?

(i had to remove parts of the code but this is on my reg page

select name="newslettereflash"
  option value="yes" selected="selected"    Yes   /option
   option value="no"    No   /option
/select

**Comment by manifestuk** [comment]
Hi Jeramiah,

This add-on really isn't supported any more, but hopefully I can guide you in the right direction. The three most frequent problems are:
1. The member field isn't being saved correctly (which is nothing to do with MCS, but prevents it from doing its work).
2. The member requires "activation" (via self-activation, or by an administrator), but that hasn't yet happened. MCS will only subscribe "activated" members.
3. The site uses some sort of member module replacement (or enhancement) which doesn't play nicely with MCS.

Do any of those apply to you?

Cheers,
Stephen

**Comment by jeramiah** [comment]
Thank you very much for your help. 

I guess 2 and 3 would apply to me.  I’m using solspace’s user module.  Also, I am having administrator approval before hand.  This helps Thanks!

Jeramiah Young

Creative Director

Support: support.foxdesignsstudio.com

Live Chat: livechat.foxdesignsstudio.com

Development Hours of Operation: Mon-Fri: 9:00am - 5:00pm

Office:  602-688-7588 Ext. 200

Toll-Free: 1-800-257-9679

Email: jeramiah@foxdesignsstudio.com

Web:  http://www.foxdesignsstudio.com/ http://www.foxdesignsstudio.com

emailsig

---

CONFIDENTIALITY NOTICE:  This email and any attachments may contain confidential or protected information that may not be further distributed by any means without permission of the sender.  If you are not the intended recipient, you are hereby notified that you are not permitted to read its content and that any disclosure, copying, printing, distribution or use of any of the information is prohibited.  If you have received this email in error, please immediately notify the sender by return e-mail and delete the message and its attachments without saving in any manner.

**Comment by jeramiah** [comment]
Yup that fixed it… working!!

Jeramiah Young

Creative Director

Support: support.foxdesignsstudio.com

Live Chat: livechat.foxdesignsstudio.com

Development Hours of Operation: Mon-Fri: 9:00am - 5:00pm

Office:  602-688-7588 Ext. 200

Toll-Free: 1-800-257-9679

Email: jeramiah@foxdesignsstudio.com

Web:  http://www.foxdesignsstudio.com/ http://www.foxdesignsstudio.com

emailsig

---

CONFIDENTIALITY NOTICE:  This email and any attachments may contain confidential or protected information that may not be further distributed by any means without permission of the sender.  If you are not the intended recipient, you are hereby notified that you are not permitted to read its content and that any disclosure, copying, printing, distribution or use of any of the information is prohibited.  If you have received this email in error, please immediately notify the sender by return e-mail and delete the message and its attachments without saving in any manner.

**Comment by manifestuk** [comment]
Glad you got it sorted.

Cheers,
Stephen
