### ISSUE TITLE
Doesn't work after EE changed the forms code

### ISSUE THREAD

**Issue by vladilin** [monooso/mailchimp_subscribe.ee_addon#7]
This stopped working after 2.5.5

Cartthrob told me EE changed their forms after their registration system stopped working. Any chance for a fix?

**Comment by manifestuk** [comment]
Not from me, sorry: I don't develop for EE any more.

Anyone else is free to fork the code and implement a solution though.

Stephen

**Comment by vladilin** [comment]
ok  :(

On Fri, Feb 22, 2013 at 10:19 PM, Stephen Lewis notifications@github.comwrote:

> Not from me, sorry: I don't develop for EE any more.
> 
> Anyone else is free to fork the code and implement a solution though.
> 
> Stephen
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/experience/mailchimp_subscribe.ee_addon/issues/7#issuecomment-13947971.

## 

Vlad Ilin
http://bkkwebdesign.com/
BKK Web Design
